import LegalLayout from "@/components/LegalLayout";

export const metadata = {
  title: "Terms of Service | Jol Energy",
};

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" updated="June 2026">
      <p>
        These Terms govern your use of the Jol Energy Intelligence Platform (the
        &ldquo;Platform&rdquo;). By accessing or using the Platform, you agree to
        these Terms.
      </p>

      <h2>The service</h2>
      <p>
        The Platform is a business intelligence dashboard for Jol Energy Pvt.
        Ltd.&rsquo;s battery-recycling operations — supplier and buyer
        pipelines, the grassroots collection network, battery-metal market
        signals, and an AI insights layer. It is provided for demonstration and
        evaluation purposes.
      </p>

      <h2>Acceptable use</h2>
      <ul>
        <li>Use the Platform only for lawful purposes.</li>
        <li>
          Do not attempt to disrupt, reverse-engineer, or gain unauthorised
          access to the Platform or its underlying services.
        </li>
        <li>
          Do not submit confidential, sensitive, or personal data into the AI
          assistant.
        </li>
      </ul>

      <h2>AI-generated content</h2>
      <p>
        Insights, narratives, and chat responses are generated by an automated
        AI model and may be incomplete or inaccurate. They are{" "}
        <strong>not</strong> financial, legal, or business advice. Always verify
        figures against the source data before acting on them.
      </p>

      <h2>Data accuracy</h2>
      <p>
        Pipeline figures are drawn from public registries and curated sample
        datasets and may not reflect real-time conditions. Provenance tooltips
        indicate sources where available.
      </p>

      <h2>No warranty</h2>
      <p>
        The Platform is provided &ldquo;as is&rdquo; without warranties of any
        kind. To the maximum extent permitted by law, Jol Energy disclaims
        liability for any damages arising from use of the Platform.
      </p>

      <h2>Changes</h2>
      <p>
        We may update these Terms from time to time. Continued use of the
        Platform after changes constitutes acceptance of the revised Terms.
      </p>

      <h2>Contact</h2>
      <p>
        For questions about these Terms, see our{" "}
        <a href="/contact">contact page</a>.
      </p>
    </LegalLayout>
  );
}
